id: dsq-747521336
date: 2007-06-20T21:35:26.0000000-07:00
author: Zack
email: zowens@eagleenvision.net
gravatar: 7e12c51b376739878fde06bb263ba577
message: <p>Vista is the best... except UAC. That doesn't work so well when you're trying to use Visual Studio.</p>
